# Nama workflow yang akan tampil di tab Actions GitHub
name: ⚠️ Build and Deploy to Clean Branch

# Pemicu: Kapan workflow ini akan berjalan
on:
  # 1. Berjalan setiap kali ada push ke branch 'main'
  push:
    branches:
      - main
  # 2. Memungkinkan Anda menjalankan workflow ini secara manual
  workflow_dispatch:

# [PENTING] Mengatur konkurensi agar tidak ada tumpukan eksekusi
concurrency:
  # Grupkan eksekusi berdasarkan commit SHA, tapi untuk `main` saja
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

# Memberikan izin yang diperlukan
permissions:
  contents: write
  # [TAMBAHAN] Izin untuk membaca status 'checks' dari workflow lain
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari branch 'main'
      # Kita tetap butuh ref dari push atau manual trigger
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------------------------------------------------------------
      # LANGKAH KUNCI BARU: Tahan dan tunggu workflow lain selesai
      # ----------------------------------------------------------------------------------
      - name: Wait for other workflows to complete
        # Hanya jalankan langkah ini jika pemicunya adalah 'push'
        if: github.event_name == 'push'
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          # [GANTI NAMA INI] Masukkan nama "check" dari workflow yang ingin ditunggu.
          # Biasanya ini adalah NAMA JOB dari file .yml tersebut.
          check-name: |
            process_and_move_articles
            build
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Waktu tunggu maksimal sebelum dianggap gagal (dalam detik)
          wait-interval: 10
      # ----------------------------------------------------------------------------------

      # Langkah 3: Cek apakah ada perubahan pada file konten yang relevan
      - name: Cek Perubahan File Konten
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            artikel/**
            ext/**
            img/**
            artikel.json
            _redirects
            _headers
            *.html
            *.xml
            *.txt
            favicon.*
            icon.*
            logo.*
            thumbnail.*
            *.webmanifest

      # Langkah-langkah berikutnya hanya berjalan JIKA ada perubahan terdeteksi
      - name: Buat direktori sementara yang bersih
        if: steps.changed_files.outputs.any_changed == 'true'
        run: mkdir deploy_dir

      - name: Salin file yang diizinkan ke direktori deploy
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          echo "✅ Perubahan terdeteksi. Memulai proses rsync..."
          rsync -av --delete \
            --include='artikel/***' \
            --include='ext/***' \
            --include='img/***' \
            --include='artikel.json' \
            --include='_redirects' \
            --include='_headers' \
            --include='*.html' \
            --include='*.xml' \
            --include='*.txt' \
            --include='favicon.*' \
            --include='icon.*' \
            --include='logo.*' \
            --include='thumbnail.*' \
            --include='*.webmanifest' \
            --exclude='.*' \
            --exclude='*' \
            ./ deploy_dir/

      - name: Deploy isi direktori bersih ke branch 'site'
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_dir
          publish_branch: site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true

      - name: Lompati Deploy
        if: steps.changed_files.outputs.any_changed != 'true'
        run: echo "👌 Tidak ada perubahan pada file konten, proses deploy dilewati."
