# Nama workflow yang akan tampil di tab Actions GitHub
name: ⚠️ Build and Deploy to Clean Branch

# Pemicu: Kapan workflow ini akan berjalan
on:
  # Berjalan setiap kali ada push ke branch 'main'
  push:
    branches:
      - main
  # Memungkinkan Anda menjalankan workflow ini secara manual
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

      # Langkah 3: Cek apakah ada perubahan pada file konten yang relevan
      - name: Cek Perubahan File Konten
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            artikel/**
            ext/**
            img/**
            artikel.json
            _redirects
            _headers
            *.html
            *.xml
            *.txt
            favicon.*
            icon.*
            logo.*
            thumbnail.*
            *.webmanifest

      # Langkah-langkah berikutnya hanya berjalan JIKA ada perubahan terdeteksi
      - name: Buat direktori sementara yang bersih
        if: steps.changed_files.outputs.any_changed == 'true'
        run: mkdir deploy_dir

      - name: Salin file yang diizinkan ke direktori deploy
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          echo "✅ Perubahan terdeteksi. Memulai proses rsync..."
          rsync -av --delete \
            --include='artikel/***' \
            --include='ext/***' \
            --include='img/***' \
            --include='artikel.json' \
            --include='_redirects' \
            --include='_headers' \
            --include='*.html' \
            --include='*.xml' \
            --include='*.txt' \
            --include='favicon.*' \
            --include='icon.*' \
            --include='logo.*' \
            --include='thumbnail.*' \
            --include='*.webmanifest' \
            --exclude='*' \
            ./ deploy_dir/

      - name: Deploy isi direktori bersih ke branch 'site'
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_dir
          publish_branch: site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true

      - name: Lompati Deploy
        if: steps.changed_files.outputs.any_changed != 'true'
        run: echo "👌 Tidak ada perubahan pada file konten, proses deploy dilewati."
