name: ⚠️ Build and Deploy to Clean Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout branch main (source)
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: source

      # Checkout branch site (target)
      - name: Checkout site branch
        uses: actions/checkout@v4
        with:
          ref: site
          path: site

      # Buat direktori sementara
      - name: Create clean directory
        run: mkdir deploy_dir

      # Salin hanya file yang diizinkan dari source
      - name: Sync allowed files to deploy directory
        run: |
          rsync -a --delete \
            --include='artikel/***' \
            --include='ext/***' \
            --include='img/***' \
            --include='artikel.json' \
            --include='_redirects' \
            --include='_headers' \
            --include='*.html' \
            --include='*.xml' \
            --include='*.txt' \
            --include='favicon.*' \
            --include='icon.*' \
            --include='logo.*' \
            --include='thumbnail.*' \
            --include='*.webmanifest' \
            --exclude='*' \
            source/ deploy_dir/

      # Bandingkan dengan branch site
      - name: Check for changes
        id: check_changes
        run: |
          rsync -a --dry-run --delete deploy_dir/ site/ > diff.log
          if [ -s diff.log ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # Deploy hanya jika ada perubahan
      - name: Deploy to site branch
        if: steps.check_changes.outputs.changed == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_dir
          publish_branch: site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
