name: 🔄 Proses Artikel (Manual Only)

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: 'Masukkan nama folder tempat file HTML akan diproses (contoh: artikelx)'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  process_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tentukan folder target
        id: set-folder
        run: |
          TARGET="${{ github.event.inputs.target_folder }}"
          if [ -z "$TARGET" ]; then
            echo "⚠️ Tidak ada input folder, fallback ke artikelx/"
            TARGET="artikelx"
          fi
          echo "TARGET_FOLDER=$TARGET" >> $GITHUB_ENV
          echo "🎯 Folder yang akan diproses: $TARGET"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ================== PROSES ARTIKEL ==================
      - name: Jalankan find-and-replace
        run: |
          for file in $TARGET_FOLDER/*.html; do
            echo "🪄 Memproses $file"
            perl -pi -w -e 's#frijal.github.io/#frijal.pages.dev/#g' "$file"
            perl -pi -w -e 's#bak.xo.je#frijal.pages.dev#g' "$file"
            perl -pi -w -e 's#https://frijal.pages.dev/assets/apple-touch-icon.png#https://frijal.pages.dev/ext/icons/apple-touch-icon.png#g' "$file"
            perl -pi -w -e 's#YOUR_APP_ID#1471267430691023#g' "$file"
            perl -pi -w -e 's#YOUR_FACEBOOK_APP_ID#1471267430691023#g' "$file"
            perl -pi -w -e 's#nama_twitter_anda#frijal#g' "$file"
            perl -pi -w -e 's/©/🄯/g' "$file"
            perl -pi -w -e 's#Komentar#Jaga Data Pribadi Tetap Aman.#g' "$file"
            perl -pi -w -e 's#Bak Xo Je#Jaga Data Pribadi Tetap Aman.#g' "$file"
          done

      - name: Inject meta & script
        run: |
          node ext/inject-meta.js || true

      - name: Tambahkan CSS/JS & div tambahan
        run: |
          echo "🧩 Menambahkan elemen tambahan ke file HTML (dengan pengecekan duplikat)..."

          # 🧾 Daftar file yang dilewati (tidak akan dimodifikasi)
          skip_files=(
            "Kalkulator-Laundry-Berkah.html"
            "Cuti-Tahun-2012.html"
          )

          # 🔁 Loop semua file HTML di folder target
          for file in "$TARGET_FOLDER"/*.html; do
            basefile="$(basename "$file")"

            # ⚙️ Cek apakah file masuk daftar pengecualian
            if [[ " ${skip_files[*]} " == *" $basefile "* ]]; then
              echo "⏭️ Lewati $file"
              continue
            fi

            echo "🔧 Memproses: $file"

            # 1️⃣ Tambahkan CSS jika belum ada
            if ! grep -q '<link rel="stylesheet" href="/ext/marquee-url.css">' "$file"; then
              sed -i '/<\/head>/i <link rel="stylesheet" href="/ext/marquee-url.css">' "$file"
            else
              echo "⏭️  CSS marquee-url.css sudah ada, lewati."
            fi

            # 2️⃣ Tambahkan div iposbrowser setelah </h1> jika belum ada
            if ! grep -q '<div id="iposbrowser"></div>' "$file"; then
              sed -i '/<\/h1>/a <div id="iposbrowser"></div>' "$file"
            else
              echo "⏭️  div#iposbrowser sudah ada, lewati."
            fi

            # 3️⃣ Tambahkan floating search container sebelum </body> jika belum ada
            if ! grep -q 'class="search-floating-container"' "$file"; then
              sed -i '/<\/body>/i <div class="search-floating-container"><input type="text" id="floatingSearchInput" placeholder="cari artikel..." autocomplete="off"><span id="floatingSearchClear" class="clear-button"></span><div id="floatingSearchResults" class="floating-results-container"></div></div>' "$file"
            else
              echo "⏭️  search-floating-container sudah ada, lewati."
            fi

            # 4️⃣ Tambahkan marquee section + JS jika belum ada
            if ! grep -q 'id="related-marquee-section"' "$file"; then
              sed -i '/<\/body>/i <section id="related-marquee-section"><div id="related-marquee-container"></div></section><script defer src="/ext/marquee-url.js"></script>' "$file"
            else
              echo "⏭️  related-marquee-section sudah ada, lewati."
            fi

            # 5️⃣ Tambahkan iposbrowser.js jika belum ada
            if ! grep -q '/ext/iposbrowser.js' "$file"; then
              sed -i '/<\/body>/i <script defer src="/ext/iposbrowser.js"></script>' "$file"
            else
              echo "⏭️  iposbrowser.js sudah ada, lewati."
            fi
          done

      # ================== SIMPAN HASIL ==================
      - name: Commit & Push perubahan
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if git diff --quiet; then
            echo "✅ Tidak ada perubahan, skip commit."
          else
            git add $TARGET_FOLDER
            git commit -m "Workflow: Proses artikel di folder $TARGET_FOLDER"
            git push
          fi
