# Nama workflow di-update untuk mencerminkan semua tugasnya
name: ☢️ Build and Generate Site Files

on:
  push:
    branches: ['main']
    # [PERBAIKAN] Pemicu dibuat lebih sensitif terhadap semua perubahan konten
    paths:
      - 'artikel/*.html'

  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '2. Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: '3. Install Dependencies'
        run: npm ci

      - name: '4. Generate artikel.json, sitemap.xml & RSS'
        run: |
          node ext/generator.js
          node ext/rss.js
        env:
          RSS_LIMIT: 30

      - name: '5. Generate screenshots'
        run: |
          npm install puppeteer --no-save
          node ext/screenshot-puppeteer.js
          
      - name: '6. Cleanup temporary files'
        run: rm -rf tmp/ __pycache__/

      # [PERBAIKAN] Semua proses commit digabungkan menjadi satu langkah
      - name: '7. Commit and Push All Generated Files'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Tambahkan semua potensi perubahan (file json, xml, rss, dan gambar baru)
          git add .

          # Cek apakah ada perubahan yang di-stage
          if git diff --staged --quiet; then
            echo "✅ Tidak ada perubahan file, tidak perlu commit."
            exit 0
          fi

          echo "✅ Perubahan ditemukan. Melakukan satu commit..."
          git commit -m "build: 🚀 Update generated site files (auto)"

          echo "🔃 Melakukan sinkronisasi dengan remote repository..."
          git pull --rebase origin main

          echo "🚀 Mendorong perubahan ke server..."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: '8. Show Published Links & Summary'
        if: always()
        run: |
          # ... (tidak ada perubahan di langkah ini) ...
          echo "✅ File yang di-generate (seharusnya):"
          echo "🔗 artikel.json: https://frijal.pages.dev/artikel.json"
          echo "🔗 sitemap.xml : https://frijal.pages.dev/sitemap.xml"
          echo "🔗 rss.xml     : https://frijal.pages.dev/rss.xml"
          echo "📊 Jumlah total artikel dan cover saat ini:"
          COUNTHTML=$(ls artikel/*.html 2>/dev/null | wc -l)
          echo "➡️  $COUNTHTML artikel di folder artikel/"
          COUNTWEBP=$(ls img/*.webp 2>/dev/null | wc -l)
          echo "➡️  $COUNTWEBP cover di folder img/"
