# Nama workflow di-update untuk mencerminkan semua tugasnya
name: ☢️ Build and Generate Site Files

on:
  push:
    branches: ['main']
    # === Pemicu kembali ke struktur 'artikel/' ===
    paths:
      - 'artikel/*.html'
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '2. Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: '3. Install Dependencies'
        run: npm ci

      - name: '4. Generate artikel.json & sitemap.xml'
        run: node ext/generator.js

      - name: '5. Generate RSS Feed'
        run: node ext/rss.js
        env:
          RSS_LIMIT: 30

      - name: '6. Commit and Push All Generated Files'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -z $(git status -s) ]]; then
            echo "✅ Tidak ada perubahan file, tidak perlu commit."
            exit 0
          fi

          echo "✅ Perubahan ditemukan. Melakukan commit..."
          git add .
          git commit -m "build: 🚀 Update file-file yang di-generate (auto)"

          echo "🔃 Melakukan sinkronisasi dengan remote repository..."
          git pull --rebase origin main

          echo "🚀 Mendorong perubahan ke server..."
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: '7. Generate screenshots'
        run: |
          npm install puppeteer --no-save
          node ext/screenshot-puppeteer.js
          
      - name: '8. Commit screenshots'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add img/
          git diff --cached --quiet || git commit -m "📸 Add article screenshots"
          git push
      
      - name: '9. Cleanup temporary files'
        run: rm -rf tmp/ __pycache__/

      - name: '10. Show Published Links & Summary'
        if: always()
        run: |
          echo "✅ File yang di-generate (seharusnya):"
          echo "🔗 artikel.json: https://frijal.pages.dev/artikel.json"
          echo "🔗 sitemap.xml : https://frijal.pages.dev/sitemap.xml"
          echo "🔗 rss.xml     : https://frijal.pages.dev/rss.xml"
          echo "📊 Jumlah total artikel dan cover saat ini:"
          COUNTHTML=$(ls artikel/*.html 2>/dev/null | wc -l)
          echo "➡️  $COUNTHTML artikel di folder artikel/"
          COUNTWEBP=$(ls img/*.webp 2>/dev/null | wc -l)
          echo "➡️  $COUNTWEBP cover di folder img/"
