name: 📋 Validasi SEO & Struktur HTML Lengkap

on:
  push:
    branches:
      - main
    paths:
      - '**.html'
      - '_headers'
      - '_redirects'
      - '*.webmanifest'
  workflow_dispatch:

jobs:
  validasi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Buat folder mini/
        run: mkdir -p mini

      - name: Validasi HTML & SEO (hanya yang gagal)
        run: |
          TANGGAL=$(date +%Y%m%d)
          LAPORAN="mini/laporan-validasi-$TANGGAL.txt"
          echo "📋 Laporan Validasi HTML & SEO (Hanya yang Gagal)" > $LAPORAN
          echo "Tanggal: $(date)" >> $LAPORAN
          echo "----------------------------------------" >> $LAPORAN

          for file in $(find . -name "*.html"); do
            GAGAL=0
            TEMP=""

            # Metadata SEO
            grep -q '<meta name="description"' "$file" || { TEMP+="❌ description MISSING\n"; GAGAL=1; }
            grep -q '<meta property="og:title"' "$file" || { TEMP+="❌ og:title MISSING\n"; GAGAL=1; }
            grep -q '<meta property="og:image"' "$file" || { TEMP+="❌ og:image MISSING\n"; GAGAL=1; }
            grep -q '<meta property="og:description"' "$file" || { TEMP+="❌ og:description MISSING\n"; GAGAL=1; }
            grep -q '<meta name="twitter:title"' "$file" || { TEMP+="❌ twitter:title MISSING\n"; GAGAL=1; }
            grep -q '<meta name="twitter:image"' "$file" || { TEMP+="❌ twitter:image MISSING\n"; GAGAL=1; }
            grep -q '<meta name="twitter:description"' "$file" || { TEMP+="❌ twitter:description MISSING\n"; GAGAL=1; }
            grep -q '<link rel="canonical"' "$file" || { TEMP+="❌ Canonical URL MISSING\n"; GAGAL=1; }

            # Struktur HTML
            grep -q '<html lang=' "$file" || { TEMP+="❌ <html lang> MISSING\n"; GAGAL=1; }
            grep -q '<meta charset=' "$file" || { TEMP+="❌ <meta charset> MISSING\n"; GAGAL=1; }
            grep -q '<title>' "$file" || { TEMP+="❌ <title> MISSING\n"; GAGAL=1; }
            grep -q '<head>' "$file" || { TEMP+="❌ <head> MISSING\n"; GAGAL=1; }
            grep -q '<body>' "$file" || { TEMP+="❌ <body> MISSING\n"; GAGAL=1; }
            grep -q '<main>' "$file" || { TEMP+="⚠️ <main> MISSING\n"; GAGAL=1; }
            grep -q '<footer>' "$file" || { TEMP+="⚠️ <footer> MISSING\n"; GAGAL=1; }

            # Heading
            H1_COUNT=$(grep -o '<h1>' "$file" | wc -l)
            if [ "$H1_COUNT" -eq 0 ]; then
              TEMP+="❌ <h1> tidak ditemukan\n"; GAGAL=1
            elif [ "$H1_COUNT" -gt 1 ]; then
              TEMP+="⚠️ Duplikat <h1> ditemukan ($H1_COUNT)\n"; GAGAL=1
            fi

            HEADINGS=$(grep -o '<h[1-6]>' "$file" | sed 's/<h\([1-6]\)>/\1/' | paste -sd " " -)
            if echo "$HEADINGS" | grep -qE '(^| )1( |$).*[^2]( |$)'; then
              TEMP+="⚠️ Urutan heading mungkin melompat: $HEADINGS\n"; GAGAL=1
            fi

            # Jika gagal, tulis ke laporan
            if [ "$GAGAL" -eq 1 ]; then
              echo "➡️ File: $file" >> $LAPORAN
              echo -e "$TEMP" >> $LAPORAN
              echo "----------------------------------------" >> $LAPORAN
            fi
          done

      - name: Linting HTML
        run: |
          TANGGAL=$(date +%Y%m%d)
          LAPORAN="mini/laporan-validasi-$TANGGAL.txt"
          echo "🧼 Linting HTML dengan HTMLHint..." >> $LAPORAN
          htmlhint "**/*.html" >> $LAPORAN || echo "⚠️ Ada peringatan dari HTMLHint." >> $LAPORAN

      - name: Konversi laporan TXT ke HTML interaktif
        run: |
          TANGGAL=$(date +%Y%m%d)
          INPUT="mini/laporan-validasi-$TANGGAL.txt"
          OUTPUT="mini/laporan-validasi-$TANGGAL.html"

          echo "<!DOCTYPE html>
          <html lang=\"id\">
          <head>
            <meta charset=\"UTF-8\">
            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
            <title>Laporan Validasi HTML & SEO - $TANGGAL</title>
            <style>
              body { font-family: sans-serif; background: #f9f9f9; padding: 2rem; line-height: 1.6; }
              h1 { color: #1e293b; }
              .file { margin-top: 2rem; padding: 1rem; background: #fff; border-left: 4px solid #e11d48; box-shadow: 0 0 4px rgba(0,0,0,0.1); }
              .ok { color: green; }
              .warn { color: orange; }
              .fail { color: red; }
              pre { white-space: pre-wrap; word-wrap: break-word; }
            </style>
          </head>
          <body>
          <h1>📋 Laporan Validasi HTML & SEO</h1>
          <p>Tanggal: $(date)</p>
          <hr>" > "$OUTPUT"

          awk '
            BEGIN { inside=0; file="" }
            /^➡️ File:/ {
              if (inside) print "</pre></div>" >> "'"$OUTPUT"'"
              file = substr($0, index($0, ":") + 2)
              print "<div class=\"file\"><strong>File:</strong> " file "<pre>" >> "'"$OUTPUT"'"
              inside=1
              next
            }
            /^❌/ { print "<span class=\"fail\">" $0 "</span>" >> "'"$OUTPUT"'" ; next }
            /^⚠️/ { print "<span class=\"warn\">" $0 "</span>" >> "'"$OUTPUT"'" ; next }
            /^✅/ { print "<span class=\"ok\">" $0 "</span>" >> "'"$OUTPUT"'" ; next }
            /^📈/ { print "<strong>" $0 "</strong>" >> "'"$OUTPUT"'" ; next }
            /^📊/ { print "<strong>" $0 "</strong>" >> "'"$OUTPUT"'" ; next }
            /^---/ { print "" >> "'"$OUTPUT"'" ; next }
            { print $0 >> "'"$OUTPUT"'" }
            END { if (inside) print "</pre></div>" >> "'"$OUTPUT"'" }
          ' "$INPUT"

          echo "</body></html>" >> "$OUTPUT"

      - name: Commit dan push laporan ke repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mini/
          git commit -m "📝 Update laporan validasi HTML & SEO $(date +'%Y-%m-%d')" || echo "Tidak ada perubahan untuk commit."
          git push origin HEAD
