name: Ping Feeds

on:
  workflow_dispatch:   # bisa dijalankan manual
  schedule:
    - cron: "0 6 * * *"   # otomatis tiap hari jam 06:00 UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping all feeds to Ping-o-Matic
        run: |
          BASE="https://frijal.pages.dev"
          FEEDS=(
            "feed-catatan-and-opini-sosial.xml"
            "feed-kuliner-gaya-hidup-and-kesehatan.xml"
            "feed-lainnya.xml"
            "feed-linux-and-open-source.xml"
            "feed-multimedia-and-editing.xml"
            "feed-sejarah-and-religi.xml"
            "feed-teknologi-web-ai-and-umum.xml"
            "rss.xml"
          )
          for f in "${FEEDS[@]}"; do
            URL="$BASE/$f"
            echo "🔔 Ping $URL"
            curl --silent --output /dev/null \
              --data "title=Frijal Pages&blogurl=$BASE/&rssurl=$URL" \
              https://pingomatic.com/ping/
          done
